### ISSUE TITLE
Can you add a custom shell command to the options?

### ISSUE THREAD

**Issue by tychop** [DKalachniuk/XcodeProjects#26]
So we can execute a custom shell command in the folder of a project.
For example you could combine multiple commands like "bundler && pod install" or maybe even commands we can't think of right now... It could be open a custom application, send a notification, create a git tag, etc etc .

**Comment by DKalachniuk** [comment]
Thank you! It is in mine todo list! 
how do you see the way of adding custom shell command to the list? Plus button and then a new window with a text field?

**Comment by tychop** [comment]
Yeah, I would imagine an entry in the settings menu to add an option to create a 'command'.
That could show a crud interface for adding/removing commands which would then become available in the menu's of each project.

**Comment by DKalachniuk** [comment]
in version 1.5 this ability is added
