### ISSUE TITLE
add custom command without name

### ISSUE THREAD

**Issue by songxing10000** [DKalachniuk/XcodeProjects#40]
First of all, this app is really awesome

![image](https://user-images.githubusercontent.com/10040131/155272371-c0dcfcc8-c0fa-4ade-937c-4b10d758453c.png)
Can you give the added command a name, the current situation should be the command name, for example, I have a package command, the name is package, the actual command is cd ./someFolder;./build.sh

**Comment by songxing10000** [comment]
Also about icon support, custom pro img, like Sourcetree
![image](https://user-images.githubusercontent.com/10040131/155272888-661b7335-4a1f-4dfd-809a-3c68a0a57182.png)

**Comment by DKalachniuk** [comment]
Thank you very much! 
Glad you like it. 

I will do that! Like your suggestions. Thank you!

**Comment by DKalachniuk** [comment]
@songxing10000 you can track the progress in this branch origin/feature/addNameToCustomCommand
support is added already. if you can test - will be awesome

**Comment by DKalachniuk** [comment]
one downside: all created commands will be removed ...

**Comment by DKalachniuk** [comment]
also new branch - origin/feature/addCustomIconToProject

will make a new release soon

**Comment by songxing10000** [comment]
great, i try

**Comment by DKalachniuk** [comment]
merged to master. Thank you for the suggestion

**Comment by songxing10000** [comment]
Thank you so much for this tool, very useful. Managing multiple projects is so easy to use. I used to have this idea, but unfortunately the technology is too poor.
